const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const base = process.env.SITE_URL || 'http://127.0.0.1:4173';
const output = path.join(__dirname, 'output/playwright');
fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await chromium.launch({ ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}), headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    await page.route('https://api.frankfurter.dev/v2/rate/**', route => {
      const [, baseCurrency, quoteCurrency] = new URL(route.request().url()).pathname.split('/').slice(-3);
      route.fulfill({ json: { date: new Date().toISOString().slice(0,10), base: baseCurrency, quote: quoteCurrency, rate: 1.25 } });
    });
    await page.goto(base + '/learn/start-here/#position-calculator');
    assert.equal(await page.locator('#estimatedLot').textContent(), '0.05');
    for (const id of ['accountSize','riskPercent','entryPrice','stopPrice']) {
      const original = await page.locator('#' + id).inputValue();
      await page.locator('#' + id).fill('');
      assert.equal(await page.locator('#estimatedLot').textContent(), '\u2014', id);
      assert.equal(await page.locator('#estimatedRisk').textContent(), '\u2014', id);
      assert.equal(await page.locator('#' + id).getAttribute('aria-invalid'), 'true');
      await page.locator('#' + id).fill(original);
    }
    await page.locator('#direction').selectOption('sell');
    assert.match(await page.locator('#riskStatus').textContent(), /stop must/);
    await page.locator('#stopPrice').fill('4510');
    assert.equal(await page.locator('#estimatedLot').textContent(), '0.05');
    await page.locator('#riskPercent').fill('.05');
    assert.equal(await page.locator('#estimatedLot').textContent(), 'No size fits');
    await page.locator('#riskPercent').fill('.5');
    for (const pair of ['EURUSD','GBPUSD','USDJPY','USDCHF','USDCAD','AUDUSD','NZDUSD']) {
      await page.locator('#instrument').selectOption(pair);
      assert.equal(await page.locator('#entryPrice').inputValue(), '');
      assert.equal(await page.locator('#estimatedLot').textContent(), '\u2014');
      await page.locator('#loadExample').click();
      assert.equal(await page.locator('#riskStatus').getAttribute('data-error'), 'false', pair);
      assert.match(await page.locator('#stopDistance').textContent(), /50 pips/);
    }
    await page.locator('#instrument').selectOption('GBPUSD');
    await page.locator('#loadExample').click();
    assert.equal(await page.locator('#estimatedLot').textContent(), '0.1');
    await page.locator('.broker-details summary').click();
    await page.locator('#brokerOverride').check();
    assert.equal(await page.locator('#estimatedLot').textContent(), '\u2014');
    await page.locator('#tickValue').fill('1');
    assert.equal(await page.locator('#estimatedLot').textContent(), '0.1');
    await page.locator('#minLot').fill('.2');
    assert.equal(await page.locator('#estimatedLot').textContent(), 'No size fits');
    await page.locator('#minLot').fill('.01');
    await page.locator('#maxLot').fill('.05');
    assert.equal(await page.locator('#estimatedLot').textContent(), '0.05');
    await page.locator('#instrument').selectOption('EURGBP');
    assert.equal(await page.locator('#brokerOverride').isChecked(), false);
    await page.locator('#loadExample').click();
    await page.waitForFunction(() => document.getElementById('conversionNote').textContent.includes('Daily reference:'));
    assert.equal(await page.locator('#riskStatus').getAttribute('data-error'), 'false');
    await page.locator('.broker-details summary').click();
    await page.locator('#position-calculator').screenshot({ path: path.join(output,'calculator-desktop.png') });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    await page.locator('#position-calculator').screenshot({ path: path.join(output,'calculator-mobile.png') });
    await page.unroute('https://api.frankfurter.dev/v2/rate/**');
    await page.route('https://api.frankfurter.dev/**', route => route.abort());
    await page.locator('#instrument').selectOption('GBPJPY');
    await page.locator('#loadExample').click();
    await page.waitForFunction(() => document.getElementById('conversionNote').textContent.includes('unavailable or out of date'));
    assert.equal(await page.locator('#estimatedLot').textContent(), '\u2014');
    await page.locator('.broker-details summary').click();
    await page.locator('#brokerOverride').check();
    await page.locator('#tickValue').fill('.63');
    assert.equal(await page.locator('#riskStatus').getAttribute('data-error'), 'false');
    await page.unroute('https://api.frankfurter.dev/**');
    await page.goto(base + '/gold-notes/gold-pips-points/');
    await page.locator('#noteStart').fill('');
    assert.equal(await page.locator('#notePipCount').textContent(), '\u2014');
    await page.locator('#noteStart').fill('4500');
    await page.locator('#noteEnd').fill('4500.05');
    await page.locator('#notePip').selectOption('0.10');
    assert.equal(await page.locator('#notePipCount').textContent(), '0.5 pips');
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    await page.route('**/embed-widget-events.js', route => route.abort());
    await page.goto(base + '/#event-calendar');
    await page.getByText('Calendar unavailable here. Open the source calendar below.').waitFor();
    await page.locator('#calendarMarket').selectOption('GBP,JPY');
    assert.match(await page.locator('#calendarWidget script').textContent(), /GBP,JPY/);
    await page.locator('#calendarImportance').selectOption('0,1');
    assert.match(await page.locator('#calendarWidget script').textContent(), /0,1/);
    await page.getByText('Calendar unavailable here. Open the source calendar below.').waitFor();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    await page.locator('#event-calendar').screenshot({ path: path.join(output,'calendar-mobile.png') });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator('#event-calendar').screenshot({ path: path.join(output,'calendar-desktop.png') });
    await page.goto(base + '/#start');
    await page.locator('.start-path li:first-child a').click();
    assert.match(page.url(), /learn\/start-here/);
    assert.deepEqual(errors, []);
    console.log('PASS: calculator validation, recovery, broker bounds, mobile overflow, calendar filters/fallback and first learning step.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
